### ISSUE TITLE
Require `ruamel.yaml` version to be greater than v18.x.x

### ISSUE THREAD

**Issue by frank-lenormand** [Avature/confight#18]
Version v18.0.0 comes with a few breaking changes:

https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/README.md

The breaking changes were mitigated in commit 96a1def.

We could now revert it, and change the use of the API in `confight`.

**Comment by jvrsantacruz** [comment]
This PR removes python2 compatibility but does not remove python2 debian packaging and builds would fail if we release a version only with this PR. 

**suggestion**: Merge this changes into #22 and perform a single change.
