### ISSUE TITLE
YAML is not supported, but declared

### ISSUE THREAD

**Issue by HaySayCheese** [Avature/confight#6]
Docs are specifying support of YAML, but it is not supported (At least in the version that is shipped by the pip by default.). 
![image](https://user-images.githubusercontent.com/528635/78806010-d3ae6d80-79ca-11ea-8160-1bff55a561fe.png)

Here is the code fragment from `confight.py`
```
FORMATS = ('toml', 'ini', 'json')
FORMAT_EXTENSIONS = {
    'js': 'json',
    'json': 'json',
    'toml': 'toml',
    'ini': 'ini',
    'cfg': 'ini',
}
FORMAT_LOADERS = {
    'json': lambda *args: json.load(*args, object_pairs_hook=OrderedDict),
    'toml': lambda *args: toml.load(*args, _dict=OrderedDict),
    'ini': load_ini
}
```

The attempt to parse YAML config results in

```
ValueError: Unknown format extension 'yaml' for '/etc/<app>/config.yaml'
```

**Comment by lasizoillo** [comment]
Yaml require a extra library and is not enabled by default as you can see here https://github.com/Avature/confight/blob/master/setup.py#L28

If you install with `pip install confight[yaml]` you get it running.

So yaml is supported, but not well documented how to do it.

**Comment by jvrsantacruz** [comment]
The documentation was updated to explicitly list the default formats and to point to the `Install` section, in which how to use yaml was shown. 

Thanks for reporting! PR are more than welcomed!
